#!/usr/bin/env python3
"""Generates unicode_s1.sql: the character tables of the SQL port of the identity keys, taken FROM the normative
validator itself (validator._CONFUSABLE, _CONFUSABLE_LOW, _IGNORABLE, _MARKS, _QUOTES, str.casefold, <wide>/<narrow>,
general categories Cf/Pd/Pi/Pf, str.isspace) — parity with Python by construction, not by hand (S21-01).
The output is pure ASCII: every character is written as a code point number or a regex escape.

Usage: python3 slice/gen_unicode_s1.py      (writes slice/unicode_s1.sql)
"""
import sys
import unicodedata
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent / "core"))
import validator as VAL  # noqa: E402
import unicodedata as _ud  # noqa: E402
assert _ud.unidata_version == VAL.UNICODE_VERSION, "generate only with the validator's pinned Unicode version"

ALL = [cp for cp in range(0x110000) if not 0xD800 <= cp <= 0xDFFF]


def ranges(cps):
    cps, out = sorted(set(cps)), []
    for cp in cps:
        if out and cp == out[-1][1] + 1:
            out[-1][1] = cp
        else:
            out.append([cp, cp])
    return out


def esc(cp):
    return f"\\u{cp:04X}" if cp <= 0xFFFF else f"\\U{cp:08X}"


def bracket(cps):
    return "[" + "".join(esc(a) if a == b else f"{esc(a)}-{esc(b)}" for a, b in ranges(cps)) + "]"


def translate_fn(name, pairs, comment, pre=""):
    """CREATE FUNCTION name(s) = translate(<pre>(s), from, to), strings built from code points at DDL time."""
    src = ",".join(str(a) for a, _ in pairs)
    dst = ",".join(str(b) for _, b in pairs)
    body = f"SELECT translate({pre or 's'}, %L, %L)"
    return f"""-- {comment}
DO $gen$ DECLARE f text; t text; BEGIN
  SELECT string_agg(chr(a), '' ORDER BY n), string_agg(chr(b), '' ORDER BY n) INTO f, t
  FROM unnest(ARRAY[{src}]::int[], ARRAY[{dst}]::int[]) WITH ORDINALITY u(a, b, n);
  EXECUTE format('CREATE OR REPLACE FUNCTION ac.{name}(s text) RETURNS text IMMUTABLE LANGUAGE sql AS %L',
                 format('{body}', f, t));
END $gen$;
"""


out = ["-- GENERATED by slice/gen_unicode_s1.py from core/validator.py - do not edit by hand.",
       f"-- Python unicodedata {unicodedata.unidata_version}. Applied after ddl_s1.sql, before keys_s1.sql.", ""]

# 1. width folding: <wide>/<narrow> -> NFKC (one code point each, except U+FFE3 -> space + U+0304)
wide = {cp: unicodedata.normalize("NFKC", chr(cp)) for cp in ALL
        if unicodedata.decomposition(chr(cp)).startswith(("<wide>", "<narrow>"))}
multi = {cp: v for cp, v in wide.items() if len(v) != 1}
assert list(multi) == [0xFFE3], multi
pairs = [(cp, ord(v)) for cp, v in sorted(wide.items()) if len(v) == 1]
out.append(translate_fn("width_fold", pairs, f"validator._width: {len(wide)} code points with <wide>/<narrow> decomposition",
                        pre="replace(s, chr(65507), chr(32) || chr(772))"))

# 2. invisible: general category Cf + validator._IGNORABLE
ign = [cp for cp in ALL if VAL._ignorable(chr(cp))]
out.append(f"""-- validator._ignorable: Cf + Default_Ignorable ranges ({len(ign)} code points)
CREATE OR REPLACE FUNCTION ac.drop_ignorable(s text) RETURNS text IMMUTABLE LANGUAGE sql AS $$
  SELECT regexp_replace(s, '{bracket(ign)}', '', 'g') $$;
""")

# 3. casefold: every code point whose str.casefold() differs (multi-character folds included)
cf = [(cp, chr(cp).casefold()) for cp in ALL if chr(cp).casefold() != chr(cp)]
rows = ",\n".join(f"({cp},ARRAY[{','.join(str(ord(x)) for x in v)}])" for cp, v in cf)
out.append(f"""-- str.casefold(): {len(cf)} code points
CREATE TABLE ac.casefold_map (ch text PRIMARY KEY, folded text NOT NULL);
INSERT INTO ac.casefold_map
SELECT chr(cp), (SELECT string_agg(chr(x), '' ORDER BY o) FROM unnest(f) WITH ORDINALITY z(x, o)) FROM (VALUES
{rows}) v(cp, f);
REVOKE ALL ON ac.casefold_map FROM PUBLIC;
CREATE OR REPLACE FUNCTION ac.casefold(s text) RETURNS text STABLE LANGUAGE sql AS $$
  SELECT coalesce(string_agg(coalesce(m.folded, c.ch), '' ORDER BY c.n), '')
  FROM regexp_split_to_table(s, '') WITH ORDINALITY AS c(ch, n) LEFT JOIN ac.casefold_map m ON m.ch = c.ch $$;
""")

# 4. dashes, quotes, whitespace (base_key tail)
dash = [cp for cp in ALL if unicodedata.category(chr(cp)) == "Pd"] + [0x2212]
quote = [cp for cp in ALL if chr(cp) in VAL._QUOTES or unicodedata.category(chr(cp)) in ("Pi", "Pf")]
space = [cp for cp in ALL if chr(cp).isspace()]
out.append(f"""-- base_key tail: Pd + U+2212 -> '-' ({len(dash)}); quotes + Pi/Pf removed ({len(quote)}); str.split() whitespace ({len(space)})
CREATE OR REPLACE FUNCTION ac.punct_space(s text) RETURNS text IMMUTABLE LANGUAGE sql AS $$
  SELECT btrim(regexp_replace(regexp_replace(regexp_replace(s,
           '{bracket(dash)}', '-', 'g'),
           '{bracket(quote)}', '', 'g'),
           '{bracket(space)}+', ' ', 'g'), ' ') $$;
""")

# 5. look-alikes -> Cyrillic (two passes) and combining accents
conf = sorted(VAL._CONFUSABLE.items())
assert all(len(v) == 1 for _, v in conf)
out.append(translate_fn("confusables", [(k, ord(v)) for k, v in conf], f"validator._CONFUSABLE ({len(conf)})"))
low = sorted(VAL._CONFUSABLE_LOW.items())
assert all(len(v) == 1 for _, v in low)
out.append(translate_fn("confusables_low", [(k, ord(v)) for k, v in low], "validator._CONFUSABLE_LOW (after casefold)"))
marks = [cp for a, b in VAL._MARKS for cp in range(a, b + 1)]
out.append(f"""-- validator._drop_marks: NFD, combining accents except breve and diaeresis removed, NFC
CREATE OR REPLACE FUNCTION ac.drop_marks(s text) RETURNS text IMMUTABLE LANGUAGE sql AS $$
  SELECT normalize(regexp_replace(normalize(s, NFD), '{bracket(marks)}', '', 'g'), NFC) $$;
""")

sql = "\n".join(out)
assert sql.isascii()
(HERE / "unicode_s1.sql").write_text(sql, encoding="utf-8")
print(f"unicode_s1.sql: width={len(wide)} ignorable={len(ign)} casefold={len(cf)} dash={len(dash)} quote={len(quote)} "
      f"space={len(space)} confusables={len(conf)} marks={len(marks)} bytes={len(sql)}")
